/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SoundCreateRouteImport } from './routes/sound/create'
import { Route as SoundGroupIdEditRouteImport } from './routes/sound/$groupId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoundCreateRoute = SoundCreateRouteImport.update({
  id: '/sound/create',
  path: '/sound/create',
  getParentRoute: () => rootRouteImport,
} as any)
const SoundGroupIdEditRoute = SoundGroupIdEditRouteImport.update({
  id: '/sound/$groupId/edit',
  path: '/sound/$groupId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sound/create': typeof SoundCreateRoute
  '/sound/$groupId/edit': typeof SoundGroupIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sound/create': typeof SoundCreateRoute
  '/sound/$groupId/edit': typeof SoundGroupIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sound/create': typeof SoundCreateRoute
  '/sound/$groupId/edit': typeof SoundGroupIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sound/create' | '/sound/$groupId/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sound/create' | '/sound/$groupId/edit'
  id: '__root__' | '/' | '/sound/create' | '/sound/$groupId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SoundCreateRoute: typeof SoundCreateRoute
  SoundGroupIdEditRoute: typeof SoundGroupIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sound/create': {
      id: '/sound/create'
      path: '/sound/create'
      fullPath: '/sound/create'
      preLoaderRoute: typeof SoundCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sound/$groupId/edit': {
      id: '/sound/$groupId/edit'
      path: '/sound/$groupId/edit'
      fullPath: '/sound/$groupId/edit'
      preLoaderRoute: typeof SoundGroupIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SoundCreateRoute: SoundCreateRoute,
  SoundGroupIdEditRoute: SoundGroupIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
